### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by Sheep975** [blake502/balatro-apk-maker#14]
Hi! I managed to build balatro for my iPhone and iPad with xcode and it runs perfectly.

Is it ok to upload my ipa without game assets to use with this tool?
Just place game.love in the Balatro.app folder and it works. (needs some changes to the code)

**Comment by blake502** [comment]
Nice work!
I'm hesitant to work on this myself, since I don't have any iOS devices to test with, and I'm totally unfamiliar with building iOS apps-- Let alone side-loading them. That said, as long as you don't include any game assets, feel free to share your work here. If we can automate it and test it properly, then I'd be happy to add iOS support to this project!

**Comment by blake502** [comment]
It's possible to integrate with WSL, but it may add some complexity-- and a prerequisite to have WSL configured. This project already invokes CLI tools for most of its tasks anyway. I'll take a look at the Love2D documentation for iOS and see if I can get it to build over WSL. If so, I'll create a new branch and request some iOS users to test things.

**Comment by blake502** [comment]
Since you have an iOS device capable of side-loading... Would you mind terribly to remove the Balatro app from your device, and try a fresh install with [this new alpha build](https://github.com/blake502/balatro-apk-maker/releases/tag/ios-support-alpha-0.1)?
Simply select "n" for "Would you like to build for Android?" and select "y" for "Would you like to build for iOS?"

**Comment by blake502** [comment]
Whoops, there was a bug in that one. Give this one a go: https://github.com/blake502/balatro-apk-maker/releases/tag/ios-support-alpha-0.1.1

**Comment by Cyphs** [comment]
Just tested on iOS 15.3.1 iPhone 12, installed via TrollStore and working fine! Resolution is a little off but perfectly playable, thanks!

**Comment by Sheep975** [comment]
Trollstore installation was also successful for me!
However, installation with altstore fails due to errors. (maybe file attribution problem)
And to fix the resolution, apply the landscape orientation patch and modify the following code in main.lua.
love.window.setMode(2, 1) → love.window.setMode(2, 1, {highdpi = true})
Thanks for your work!
<img width="375" alt="AC1AB8B6-A0BF-4E9B-85A6-FDAEB7CD6D02" src="https://github.com/blake502/balatro-apk-maker/assets/67822493/44308dad-120e-46f6-a516-4d4b3306e728">

**Comment by Sheep975** [comment]
Hi! I managed to fix the file attribution problem.
Python can edit the zip with unix file attribution, and this code is worked for me!
Can you implement this instead of current method?
```
import zipfile
existing_zip = zipfile.ZipFile('balatro-base.zip', 'a')
new_file_path = 'game.love'
existing_zip.write(new_file_path, arcname='Payload/Balatro.app/game.love')
existing_zip.close()
```
<img width="378" alt="30F8FA91-4682-41D9-AD7B-43D508F80B20" src="https://github.com/blake502/balatro-apk-maker/assets/67822493/0169b5a9-6a20-4230-85ab-c464e80a2601">

**Comment by blake502** [comment]
Done. Balatro APK Maker now (experimentally) supports iOS.
Give it a try on beta-0.6!

**Comment by Sheep975** [comment]
It's working perfectly fine! Thanks for implementing my code :)
Finally, is it possible to change the location of save file?
Currently they are stored in /Library/Application Support/, but if they could be changed to /Documents/, they would be accessible to non-jailbreak users.
![IMG_0025](https://github.com/blake502/balatro-apk-maker/assets/67822493/73ebdae4-9943-4be3-a6f8-de77ec67a5b4)
