### ISSUE TITLE
Failed to sign APK

### ISSUE THREAD

**Issue by Haytham155** [blake502/balatro-apk-maker#7]
tips:
Signing APK...
Failed to sign APK!
Press any key to exit...

May I ask why this problem occurred and how should I solve it?

**Comment by blake502** [comment]
For anybody who encounters this problem in the future-- It sounds like uber-apk-signer.jar was corrupted. Since that's the largest tool, it's reasonable to assume that it's the most likely one to become corrupted. For example, if your internet dropped briefly during the download, it could corrupt some of the tools. I'd advise running in "verbose mode" to get a real error message.
