### ISSUE TITLE
Support for Quest VR Headset

### ISSUE THREAD

**Issue by Steve-XM** [blake502/balatro-apk-maker#9]
Hello,

I was able to get this .apk running on a Quest 3 VR Headset, unfortunately the resolution that the .apk makes displays very low in the VR Headset. I tried using all the different settings in the .apk to make it more viewable, but nothing worked.

If you could some how lock the resolution to something like 2k or 4k, maybe it would show up better in the headset.

Regards,

Virtual Steve

**Comment by blake502** [comment]
Hey Steve,

This is outside of the scope of this project. That said-- I'm not opposed to merging a PR to support this.

**Comment by Steve-XM** [comment]
> Hey Steve,
> 
> This is outside of the scope of this project. That said-- I'm not opposed to merging a PR to support this.

I found a fix for this btw using a 3rd party app. I am making a video that should be coming out in the next week that will have all the juicy details.  Thanks for making this.....it's so addictive.

**Comment by blake502** [comment]
Seems like a reasonable solution-- Since I don't plan to support VR headsets, an additional tool seems like a good solution.
If another developer sees this and knows how to support this without additional tools, I'll gladly re-open this issue or merge a PR for it.
With all that said-- I _do_ own a Quest 2. So maybe I'll look into it myself once this tool is in a better spot.
